name: Build and Publish Plugins to GitHub Packages

on:
  push:
    branches:
      - master # Reverted trigger to master branch

jobs:
  discover_plugins:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.find_plugins.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Find plugins with manifest.json
        id: find_plugins
        run: |
          echo "Starting plugin discovery..."
          PLUGINS_JSON="[]"
          # Use process substitution to avoid subshell for the while loop
          while IFS= read -r dir; do
            echo "Processing directory: $dir"
            # Determine build command
            BUILD_CMD="npm run build" # Default
            if [[ -f "$dir/build.sh" ]]; then
              BUILD_CMD="./build.sh"
              echo "  Found build.sh, using build_cmd: $BUILD_CMD"
            elif ! grep -q '"build":' "$dir/package.json" 2>/dev/null; then
               echo "  Warning: No build script found in $dir/package.json and no build.sh found. Skipping build command."
               BUILD_CMD="echo 'No build command configured'" # Fallback safely
            else
              echo "  Found 'build' script in package.json, using build_cmd: $BUILD_CMD"
            fi
            # Add to JSON array (simple jq append)
            echo "  Adding $dir to JSON..."
            PLUGINS_JSON=$(echo "$PLUGINS_JSON" | jq --arg name "$dir" --arg cmd "$BUILD_CMD" '. + [{"name": $name, "build_cmd": $cmd}]')
            echo "  Current PLUGINS_JSON: $PLUGINS_JSON"
          done < <(find . -maxdepth 2 -name manifest.json -printf '%h\n' | sed 's|^\./||')

          echo "Final PLUGINS_JSON array: $PLUGINS_JSON"
          # Wrap the array in an object with the key "include" for the matrix
          MATRIX_JSON_OBJ=$(echo "$PLUGINS_JSON" | jq '{"include": .}' | jq -c .)
          echo "matrix<<EOF" >> $GITHUB_OUTPUT
          echo "$MATRIX_JSON_OBJ" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "Discovered plugins matrix output object: $MATRIX_JSON_OBJ"
        shell: bash

  build_and_package:
    needs: discover_plugins
    if: ${{ needs.discover_plugins.outputs.matrix != 'null' && fromJSON(needs.discover_plugins.outputs.matrix).include[0] != null }}
    runs-on: ubuntu-latest
    # Add permissions for GitHub Packages
    permissions:
      contents: read # Needed for checkout
      packages: write # Needed to publish packages
    strategy:
      matrix: ${{ fromJSON(needs.discover_plugins.outputs.matrix) }}
      fail-fast: false

    steps:
      - name: Checkout code
        # Need full history to diff against merge base for change detection
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Reintroduce change detection
      - name: Check for changes in ${{ matrix.name }}
        id: check_changes
        run: |
          echo "Checking for changes in ${{ matrix.name }} between ${{ github.event.before }} and ${{ github.sha }}"
          # Compare HEAD with the base of the push (merge base with master)
          git diff --quiet ${{ github.event.before }} ${{ github.sha }} -- ${{ matrix.name }}/ || echo "changed=true" >> $GITHUB_OUTPUT
          # Note: This diff logic might need refinement based on your branching strategy
        shell: bash

      - name: Set up Node.js
        # Run only if changes were detected OR if it's the first push (before is 000...)
        if: steps.check_changes.outputs.changed == 'true' || github.event.before == '0000000000000000000000000000000000000000'
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: '${{ matrix.name }}/package-lock.json'

      - name: Extract package version
        # Run only if changes were detected OR if it's the first push
        if: steps.check_changes.outputs.changed == 'true' || github.event.before == '0000000000000000000000000000000000000000'
        id: get_version
        working-directory: ./${{ matrix.name }}
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"

      - name: Build ${{ matrix.name }}
        if: steps.check_changes.outputs.changed == 'true' || github.event.before == '0000000000000000000000000000000000000000'
        working-directory: ./${{ matrix.name }}
        run: |
          echo "Installing dependencies for ${{ matrix.name }}..."
          npm ci
          echo "Building ${{ matrix.name }}..."
          ${{ matrix.build_cmd }}

      - name: Package ${{ matrix.name }}
        if: steps.check_changes.outputs.changed == 'true' || github.event.before == '0000000000000000000000000000000000000000'
        working-directory: ./${{ matrix.name }}
        run: |
          echo "Running package script for ${{ matrix.name }}..."
          if grep -q '"package":' package.json; then
             npm run package
          else
             echo "Error: 'package' script not found in ${{ matrix.name }}/package.json"
             exit 1
          fi

      - name: List root directory before publish
        if: steps.check_changes.outputs.changed == 'true' || github.event.before == '0000000000000000000000000000000000000000'
        run: ls -la

      # Replace Upload Artifact with Publish to GitHub Packages
      - name: Publish ${{ matrix.name }} to GitHub Packages
        if: steps.check_changes.outputs.changed == 'true' || github.event.before == '0000000000000000000000000000000000000000'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PLUGIN_NAME: ${{ matrix.name }}
          PLUGIN_VERSION: ${{ steps.get_version.outputs.version }}
          OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          TARBALL="${PLUGIN_NAME}.tar.gz"
          CHECKSUM="${PLUGIN_NAME}.tar.gz.sha256"
          PACKAGE_URL="https://maven.pkg.github.com/${OWNER}/${REPO_NAME}/${PLUGIN_NAME}/${PLUGIN_VERSION}"

          echo "Uploading $TARBALL to ${PACKAGE_URL}/${TARBALL}"
          curl -X PUT -u "${OWNER}:${GITHUB_TOKEN}" \
               "${PACKAGE_URL}/${TARBALL}" \
               --upload-file "${TARBALL}"

          echo "Uploading $CHECKSUM to ${PACKAGE_URL}/${CHECKSUM}"
          curl -X PUT -u "${OWNER}:${GITHUB_TOKEN}" \
               "${PACKAGE_URL}/${CHECKSUM}" \
               --upload-file "${CHECKSUM}"

  # Removed the create_release job 